### ISSUE TITLE
Permanban Compatibility with SB

### ISSUE THREAD

**Issue by tr12345** [CreaturePhil/Showdown-Boilerplate#99]
Alright so not too long ago, I was facing an issue with permabanning users, especially after using `git pull` on my server. When one of my Leaders was using permaban/permalock, it gave this error: `CRASH: TypeError: userT.ban is not a function`. At the same time, this prevented my users from using /ban [ip] and /rangelock saying `CRASH: TypeError: Cannot read property '45.32.147.109' of undefined` and `CRASH: TypeError: Cannot read property 'vultr.com' of undefined`. I was hoping that you could find a fix for these. Also because of the error, some people changed their forked repository to `Pokemon-Showdown` to start up their server.

**Comment by TheFenderStory** [comment]
I just investigated this problem and it appears that the main PS repository also has a problem with rangelock and banip. Specifically a crash due to `Punishments.lockedRanges` and `Punishments.bannedIPs` being undefined when its checked for in the commands. In terms of the crashes you gave us, it would be helpful if we could get more information, like a full error stack message. I couldn't reproduce similar crashes other then the ones i mentioned.

**Comment by tr12345** [comment]
![banip error](https://cloud.githubusercontent.com/assets/10525341/15634362/eaff781e-258f-11e6-9c67-30789bd7657c.PNG)
![permalock error](https://cloud.githubusercontent.com/assets/10525341/15634364/f540b5fe-258f-11e6-9c22-573120add15f.PNG)

These might help. And while reading in development on main, I did see a few users talking about how `/rangelock` wasn't able to function very well or possibly at all.

**Comment by TheFenderStory** [comment]
For the first error @tr12345, its exactly what i was describing, the problem is due to an error with Main's new punishments api. I talked to a developer on main and we are looking into fixing that. As for the second one, boilerplate doesn't have that permaban.js file you are using. I think your problem is because the file needs to be updated to reflect the new punishments api. If you'd like to send me the code i could probably help you do that.

**Comment by tr12345** [comment]
Here you go: http://pastebin.com/jJLMXWzy. 

Thank you very much @TheFenderStory. I kinda suspected `punishments.js` being one of the error because that was the code that pretty much had ban and lock all over the file. But yeah, regarding `permaban.js` I knew that you guys didn't have it as a plugin when users fork your repository, however I believe a lot of servers have it here as an extra defense mechanism for trolls xD. Anyways, thank you lots!

**Comment by TheFenderStory** [comment]
[http://pastebin.com/9uvGGuCU](http://pastebin.com/9uvGGuCU) Here you go. This should do the trick. :)

**Comment by tr12345** [comment]
Thank you very much @TheFenderStory. I'll report back to you if there's any errors within the file or any other unique crashes via `punishments.js`. :)
